### PR TITLE
Up-grade wagtail.

### PR DESCRIPTION
**Pull request by Mhlengi**
This change is [Reviewable](https://reviewable.io/reviews/kagiso-future-media/kagiso_image/1)

### CODE REVIEW

**Comment by lee-kagiso** [comment]
Detailed pr description on what was done and why

**Comment by lee-kagiso** [comment]
Version needs to be bumped

**Comment by lee-kagiso** [comment]
Requiredments.txt needs to be updated

**Comment by lee-kagiso** [comment]
Can you confirm that this solves whatever problem is being experienced (as per the currently blank pr description)?

**Comment by Mhlengi** [comment]
Since we updating wagtail for zalebs project all most of the test cases were failing. The reason some fields are required. Example: Author, Abstract etc. Therefore, Kagiso_image app also requires wagtail update.

**Comment by lee-kagiso** [comment]
Pushed to pypi

**Pull request merged**
